const tasksActionTypes = {
  ADD_NEW_TASK: 'ADD_NEW_TASK',
  DELETE_TASK: 'DELETE_TASK',
  TASK_STATUS_ACTIVE: 'TASK_STATUS_ACTIVE',
  TASK_STATUS_COMPLETED: 'TASK_STATUS_COMPLETED',
  STATUS_FILTER: 'STATUS_FILTER'
};

export default tasksActionTypes;